
PP-Module for Mobile Device Management Agents 
===========

image:https://img.shields.io/badge/Build-master-black.svg[Master Badges]
image:https://github.com/commoncriteria/mdm-agent/workflows/Build/badge.svg[Build]
image:https://github.com/commoncriteria/mdm-agent/workflows/Validate/badge.svg[Validate]

image:https://raw.githubusercontent.com/commoncriteria/mdm-agent/gh-pages/build-branch-badge.svg[Last
QuickBuilt Branch]
https://github.com/commoncriteria/mdm-agent/blob/gh-pages/ValidationReport.txt[image:https://raw.githubusercontent.com/commoncriteria/mdm-agent/gh-pages/validation.svg[Validation]]
https://github.com/commoncriteria/mdm-agent/blob/gh-pages/SanityChecksOutput.md[image:https://raw.githubusercontent.com/commoncriteria/mdm-agent/gh-pages/warnings.svg[SanityChecks]]
https://github.com/commoncriteria/mdm-agent/blob/gh-pages/SpellCheckReport.txt[image:https://raw.githubusercontent.com/commoncriteria/mdm-agent/gh-pages/spell-badge.svg[SpellCheck]]
https://commoncriteria.github.io/mdm-agent[image:https://github.com/commoncriteria/mdm-agent/actions/workflows/quick_build.yml/badge.svg[QuickBuild]]

https://github.com/commoncriteria/mdm-agent/issues[image:https://img.shields.io/github/issues/commoncriteria/mdm-agent.svg?maxAge=2592000[GitHub
issues Open]]
image:https://img.shields.io/badge/license-Unlicensed-blue.svg[license]

This repository hosts the draft version of the Protection Profile for
QQQQ based on the
https://commoncriteria.github.io/pp/QQQQ/QQQQ-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found link:QQQQ[here].

=== Draft Version

* https://commoncriteria.github.io/mdm-agent/master/mdm-agent-release.html[Protection
Profile for QQQQ] (html)
* https://commoncriteria.github.io/mdm-agent/master/mdm-agent-release.pdf[Protection
Profile for QQQQ] (pdf)

=== Release Version

* link:QQQQ[Protection Profile for QQQQ]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/QQQQ/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/qqqq.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
